import type { Metadata, Viewport } from "next";
import { Poppins } from "next/font/google";
import "@/components/globals.css";
import Navbar from "@/components/navbar";

const poppins = Poppins({ weight: ["400", "600"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#b88e2f" },
    {
      media: "(prefers-color-scheme: dark)",
      color: "#b88e2f",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased flex flex-col`}>
        <Navbar />
        <div className="flex-1">{children}</div>
        <div>footer</div>
      </body>
    </html>
  );
}
